# Generated by Django 3.0.4 on 2020-04-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts_training', '0016_auto_20200325_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Department Name')),
                ('person', models.CharField(help_text='Person in charge of the department', max_length=50)),
                ('email', models.EmailField(help_text='Email address of the person in charge', max_length=254)),
                ('weight', models.IntegerField(unique=True)),
                ('department_icon', models.CharField(default='fa fa-', help_text='From <a href="https://fontawesome.com/icons?d=gallery&m=free">Font Awesome 5</a>. Example: <code>fas fa-user</code>.', max_length=25, verbose_name='Icon Code')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='Site_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=25, verbose_name='Page Name')),
                ('weight', models.IntegerField()),
                ('primary', models.BooleanField(default=False)),
                ('viewName', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('iconRef', models.CharField(help_text='From Font Awesome 5', max_length=25, verbose_name='Icon Code')),
            ],
            options={
                'verbose_name': 'Site Page',
                'ordering': ['weight'],
            },
        ),
        migrations.AlterField(
            model_name='planned_session',
            name='trainingId',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='trainingId',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconRef', models.CharField(help_text='From <a href="https://fontawesome.com/icons?d=gallery&m=free">Font Awesome 5</a>. Example: <code>fas fa-user</code>.', max_length=25, verbose_name='Icon Code')),
                ('iconName', models.CharField(max_length=25, verbose_name='Category Name')),
                ('weight', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, help_text="Department this category belongs to. If you're using departments, you <strong>must</strong> set this for the category to appear.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ts_training.Department')),
            ],
            options={
                'verbose_name': 'Training Category',
                'verbose_name_plural': 'Training Categories',
                'ordering': ['weight'],
            },
        ),
        migrations.AlterField(
            model_name='training_spec',
            name='category',
            field=models.ForeignKey(limit_choices_to={'itemType': 'CAT'}, on_delete=django.db.models.deletion.CASCADE, to='ts_training.Category'),
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
