# Generated by Django 3.0.4 on 2020-04-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts_training', '0017_auto_20200401_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planned_session',
            name='trainingId',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='trainingId',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
        migrations.AlterField(
            model_name='training_spec',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_training.Category'),
        ),
    ]
